name: build-push-image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Private Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (tag is the commit SHA)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}
      - name: Build and push Docker image (tag is 'latest')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:latest
      - name: clone namespace-deployment repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/namespace-deployment
          path: namespace-deployment
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          ref: main
      - name: Update image tag in deployment.yaml
        uses: mikefarah/yq@v4.49.2
        run: |
          cd namespace-deployment
          jq -i '.spec.template.spec.containers[0].image = "ghcr.io/'"${{ github.repository_owner }}"'/my-image:'"${{ github.sha }}"'"' deployment.yaml
      - name: Commit and push changes with secrets.DEPLOYMENT_TOKEN with write access
        run: |
          cd namespace-deployment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
      - name: Clean up
        run: |
          rm -rf namespace-deployment
